[platformio]
default_envs = worker_tag

[env:worker_tag]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -D DEVICE_ID=\"worker-tag-1\"
  -D BASE_STATION_URL=\"http://10.152.83.65:8090\"
