[platformio]
default_envs = node1

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = https://github.com/Fhilb/DW3000_Arduino.git

[env:node1]
build_flags =
  -DNODE_ID=1
  -DINITIATOR_NODE_ID=1
  -DNUM_NODES=3
  -DSINGLE_PAIR_DEBUG_MODE=0

[env:node2]
build_flags =
  -DNODE_ID=2
  -DINITIATOR_NODE_ID=1
  -DNUM_NODES=3
  -DSINGLE_PAIR_DEBUG_MODE=0

[env:node3]
build_flags =
  -DNODE_ID=3
  -DINITIATOR_NODE_ID=1
  -DNUM_NODES=3
  -DSINGLE_PAIR_DEBUG_MODE=0

[env:node4]
build_flags =
  -DNODE_ID=4
  -DINITIATOR_NODE_ID=1
  -DNUM_NODES=3
  -DSINGLE_PAIR_DEBUG_MODE=0
